image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install
    command: cd gym-ui/ && npm install
  
  - init: npm start
    command: cd gym-ui/ && npm start

ports:
  - port: 3000
    onOpen: open-preview

