version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "gym-ui/package-lock.json" }}

      - run:
          name: Install dependencies
          command: cd gym-ui/ && npm install

      - save_cache:
          key: dependency-cache-{{ checksum "gym-ui/package-lock.json" }}
          paths:
            - ./gym-ui/node_modules